# Generated by Django 3.2.3 on 2021-08-21 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.CharField(editable=False, max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('input_info', models.CharField(max_length=200)),
                ('output_info', models.CharField(max_length=200)),
                ('data', models.JSONField()),
                ('level', models.CharField(choices=[('Oson', 'Oson'), ("O'rtacha", "O'rtacha"), ('Murakkab', 'Murakkab')], max_length=25)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
